module.exports = [
	require("./admin"),
	require("./info"),
	require("./join"),
	require("./motd"),
	require("./nick"),
	require("./part"),
	require("./ping"),
	require("./pong"),
	require("./privmsg"),
	require("./quit"),
	require("./time"),
	require("./topic"),
	require("./user"),
	require("./whois"),
];